import "./globals.css";
import type { Metadata } from "next";
import { NavBar } from "@/ui/organisms/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomePage({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">

      <body className="">
        <section>
        <NavBar/>
        {children}
        </section>
  
        </body>

    </html>
  );
}
