import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/ui/organisms/Header";
import { Footer } from "@/ui/organisms/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function HomePage({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<Header />

				<section className="mx-auto max-w-7xl p-8">
					{children}
				</section>
				{modal}
				<Footer />
			</body>
		</html>
	);
}
